### ISSUE TITLE
请问那个tags的md文件怎么写呀，不好意思，能否给我看下你的md文件参考一下？

### ISSUE THREAD

**Issue by YBFJ** [Longlongyu/hexo-theme-Cxo#13]
你好主要问题如题，另外想请问下你这个update博客的时间可以加上具体的时间吗？比如几点几分这个样子？只有日期感觉不是很清楚，嘿嘿

**Comment by Longlongyu** [comment]
``` md
title: Tags
date: 2014-12-22 12:39:04
type: "tags"
comments: false
---
```
hexo根目录的source目录下新建个tags文件夹，在当中新建index.md，填入上面的内容就行。

时间戳也一个点，会加入的。

😆 感谢支持！

**Comment by YBFJ** [comment]
@Longlongyu 谢谢你的回复，我尝试了你的办法，还是有如下的问题，1. 我直接加入你说的这个，在网页里面只是显示Tag - 0，我需要用什么特殊的语法吗？ 比如我想在标签页加入 HTML css vue 这3个标签应该怎么写呢？ 2. 如果我在写博文的时候想要为我的博文加上相应的标签，我应该怎么写呢？
另外你的这个博客主题样式的缩略图好评哦！！！！

**Comment by Longlongyu** [comment]
😆 在hexo目录输入指令`hexo new <title>`即可创建新文章，例如`hexo new wenzhang`。
指令会在`\source\_posts`创建好文章，date也会配置好。

tags页配置后，则不需要再去修改他，hexo会获取tags数。

文章的tags则需要手动添加，可以参考下面
``` yaml
---
title: 标题
date: 2018-06-28 14:39:37
updated: 2018-07-6 17:50:33
abstract: 我是摘要部分。
tags:
- vue
- HTML
- css
---
```

更多相关知识可以到 [hexo官网](https://hexo.io/zh-cn/docs/writing.html) 了解
